/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_king_testuninstalldemo_MainActivity */

#ifndef _Included_com_example_king_testuninstalldemo_MainActivity
#define _Included_com_example_king_testuninstalldemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_king_testuninstalldemo_MainActivity
 * Method:    Uninstall
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_king_testuninstalldemo_MainActivity_Uninstall
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
